import type { GuideContent } from './types';

export const es: GuideContent = {
  ui: {
    searchLabel: 'Buscar en la guía',
    searchPlaceholder: 'Seguimiento, marcadores, atajos…',
    navigationLabel: 'Guía de usuario',
    mobileNavigationLabel: 'Guía de usuario (móvil)',
    browseSections: 'Ver secciones',
    resultCount: (count) => `${count} resultado${count === 1 ? '' : 's'}`,
    noResults: 'Ninguna sección coincide con esta búsqueda.',
    onThisPage: 'En esta página',
    video: 'VÍDEO',
    videoOffline: 'Este vídeo se reproduce desde la guía de usuario en línea. Conéctate a internet para verlo.',
    result: 'Resultado:',
  },
  title: 'Guía de usuario de Annotate',
  lede: 'Documentación sobre la creación de proyectos, la captura de clips, la anotación, el seguimiento, los marcadores, las presentaciones, la exportación y el almacenamiento de proyectos.',
  groups: [
    {
      label: 'Para empezar',
      links: [
        { id: 'orientation', label: 'Visión general', summary: 'Estructura de un proyecto y el modelo de clips, marcadores y presentaciones.', keywords: 'visión general introducción modelo' },
        { id: 'videos', label: 'Tutoriales en vídeo', summary: 'Doce grabaciones breves de los flujos de trabajo principales.', keywords: 'vídeo tutorial demostración ver grabación' },
        { id: 'first-project', label: 'Primer proyecto', summary: 'De un proyecto vacío a un clip con un marcador.', keywords: 'crear importar demostración' },
        { id: 'installation', label: 'Instalar y ejecutar', summary: 'Descargas, inicio y servicios locales.', keywords: 'instalación inicio mac windows escritorio navegador' },
      ],
    },
    {
      label: 'Flujos de trabajo',
      links: [
        { id: 'capture', label: 'Capturar y etiquetar', summary: 'Convertir fases de juego en clips que pueden solaparse.', keywords: 'panel modificador línea de tiempo etiquetado reetiquetar' },
        { id: 'clip-editor', label: 'Editar un clip', summary: 'Dibujar y animar formas, y recortar el clip.', keywords: 'fotograma clave línea de tiempo rectángulo círculo flecha polígono recortar' },
        { id: 'tracking', label: 'Seguir y corregir', summary: 'Seguir jugadores, corregir errores y poner nombre a los resaltados.', keywords: 'seguimiento jugador resaltado solapamiento nombre etiqueta' },
        { id: 'pins', label: 'Marcadores y animaciones', summary: 'Anotar fotogramas exactos y mostrar las anotaciones paso a paso.', keywords: 'fotograma fijo conjunto de anotaciones animación' },
        { id: 'homography', label: 'Dibujar sobre el campo', summary: 'Homografía y rectángulos y círculos sobre el campo.', keywords: 'homografía campo cuadrícula calcular mostrar eliminar' },
        { id: 'presentations', label: 'Presentaciones', summary: 'Crear y reproducir secuencias de clips, marcadores y títulos.', keywords: 'diapositivas presentar transición vídeo del partido' },
        { id: 'export-recovery', label: 'Exportar y recuperar', summary: 'Informes, imágenes, papelera y comprobaciones de integridad.', keywords: 'png csv json copia de seguridad restaurar papelera' },
      ],
    },
    {
      label: 'Referencia',
      links: [
        { id: 'workspace-map', label: 'Espacios de trabajo', summary: 'Dónde se hace cada tipo de trabajo.', keywords: 'página del proyecto captura editor presentación metadatos' },
        { id: 'drawing-tools', label: 'Herramientas de dibujo', summary: 'Comportamiento de las herramientas y sistemas de coordenadas.', keywords: 'seleccionar resaltado texto estilo campo imagen' },
        { id: 'keyboard', label: 'Atajos de teclado', summary: 'Teclas de reproducción, edición y presentación.', keywords: 'atajos comandos espacio eliminar deshacer' },
        { id: 'glossary', label: 'Glosario', summary: 'Definiciones de los conceptos de Annotate.', keywords: 'términos definiciones clip marcador fotograma clave' },
        { id: 'project-files', label: 'Archivos del proyecto', summary: 'Almacenamiento local y copias de seguridad seguras.', keywords: 'carpeta proyecto json medios análisis exportaciones papelera' },
        { id: 'troubleshooting', label: 'Solución de problemas', summary: 'Fallos habituales y primeras comprobaciones.', keywords: 'sin conexión ventana lento error modelo' },
      ],
    },
  ],
  tutorials: {
    'first-project': { title: 'Tu primer proyecto', description: 'Crear un proyecto, importar el vídeo de un partido, capturar una posesión con un modificador, abrir el editor de clips y añadir un marcador.' },
    'capture-tagging': { title: 'Capturar y etiquetar una jugada', description: 'Etiquetar un partido mientras se reproduce, con clips solapados y un modificador; después reetiquetar un clip y ampliar la línea de tiempo.' },
    'clip-editing': { title: 'Dibujar y animar formas', description: 'Dibujar un rectángulo, moverlo para crear fotogramas clave, cambiar su tamaño y girarlo, añadir un círculo y cambiar el estilo de ambos a la vez.' },
    'clip-trimming': { title: 'Recortar un clip', description: 'Arrastrar los dos tiradores hacia dentro, revisar el resumen, aplicar el recorte y deshacerlo enseguida.' },
    'basic-tracking': { title: 'Seguir a un jugador', description: 'Elegir un jugador entre los resaltados provisionales, iniciar el seguimiento, detenerlo y revisar el resultado a velocidad normal.' },
    'tracking-correction': { title: 'Corregir un seguimiento', description: 'El seguimiento salta al jugador equivocado. Volver al último fotograma correcto, repetir el seguimiento, avanzar un fotograma cuando se pierde al jugador y continuar.' },
    'tracking-refinements': { title: 'Nombrar jugadores y unir una flecha', description: 'Poner nombre a dos resaltados seguidos, mostrar sus nombres en el vídeo y unir una flecha a ambos para que los siga.' },
    'pin-annotation': { title: 'Anotar un marcador', description: 'Añadir un marcador, resaltar a dos jugadores, unirlos con una flecha, cambiar su estilo, guardar y cerrar el marcador.' },
    'pin-animations': { title: 'Animar un marcador', description: 'Hacer que las anotaciones de un marcador aparezcan paso a paso, previsualizar la secuencia y reproducir el clip hasta el marcador.' },
    homography: { title: 'Dibujar sobre el campo', description: 'Calcular la homografía, comprobar la cuadrícula del campo, dibujar un rectángulo sobre el campo y reproducir un movimiento de cámara.' },
    'presentation-authoring': { title: 'Crear y presentar una presentación', description: 'Crear una presentación, añadir un clip, un marcador y un título, elegir dónde se pausa el clip y presentarla.' },
    'export-recovery': { title: 'Exportar y recuperar', description: 'Exportar un informe, encontrar sus archivos, eliminar un clip y deshacer la eliminación, y hacer una copia de seguridad de la carpeta del proyecto.' },
  },
  overview: {
    title: 'Visión general',
    paragraphs: [
      'Annotate es una aplicación local para el análisis de vídeo de fútbol. Un proyecto contiene vídeos importados, clips capturados, marcadores, datos de anotación, presentaciones, exportaciones, cachés y una papelera recuperable.',
      'Las anotaciones de clip son objetos con fotogramas clave que se dibujan sobre el vídeo. Las anotaciones de marcador son documentos asociados a un fotograma exacto del vídeo de origen y pueden incluir animaciones de entrada. El seguimiento genera los fotogramas clave de los resaltados, y la homografía proporciona coordenadas de campo para rectángulos y círculos.',
      'Los datos se guardan en la carpeta del proyecto elegida. La aplicación se comunica con un servicio de Python en el mismo ordenador para importar vídeo, seguir jugadores, calcular la homografía y exportar. Las versiones de escritorio incluyen y gestionan ese servicio; en el desarrollo con navegador se ejecuta por separado.',
    ],
    cards: [
      ['Clip', 'Un intervalo semiabierto de fotogramas dentro de un vídeo importado.'],
      ['Marcador', 'Un fotograma exacto dentro de un clip, con cero o más conjuntos de anotaciones.'],
      ['Presentación', 'Una secuencia ordenada de clips, marcadores y títulos.'],
    ],
  },
  videos: {
    title: 'Tutoriales en vídeo',
    intro: 'Cada sección siguiente incluye una breve grabación de la aplicación real, que se reproduce desde la [guía de usuario en línea](https://patrickjykang.github.io/annotate-docs/es/), donde también hay un vídeo de 13 minutos con todo el flujo de trabajo. Las grabaciones no tienen sonido, llevan subtítulos y siguen el idioma elegido en el encabezado. Selecciona un tutorial para ir a él.',
  },
  firstProject: {
    title: 'Primer proyecto',
    intro: 'El siguiente procedimiento crea un proyecto, importa el vídeo de un partido, captura un clip y le añade un marcador. El dibujo, el seguimiento, las presentaciones y la exportación se tratan en secciones posteriores.',
    steps: [
      { title: 'Crear el proyecto', location: 'Pantalla de inicio', action: 'Elige **Crear proyecto**, introduce los datos del partido que conozcas y selecciona una carpeta.', result: 'Annotate crea una carpeta de proyecto normal y abre la página del proyecto.' },
      { title: 'Importar un vídeo', location: 'Página del proyecto · Vídeos', action: 'Elige **Importar vídeo…** y selecciona el archivo del partido. Mantén Annotate abierto mientras se prepara el vídeo.', result: 'El vídeo aparece en el proyecto con su frecuencia de fotogramas y resolución originales.' },
      { title: 'Capturar un clip', location: 'Reproductor de captura', action: 'Abre el reproductor de captura, reproduce el vídeo, haz clic en una casilla del panel en el primer fotograma de la jugada, añade los modificadores que quieras y vuelve a hacer clic en la misma casilla en el último fotograma.', result: 'Aparece un clip etiquetado en la línea de tiempo y en la lista de clips.' },
      { title: 'Abrir el clip y añadir un marcador', location: 'Editor de clips', action: 'Selecciona el clip y elige **Abrir editor**. Ve al fotograma que quieras explicar y elige **Añadir marcador**.', result: 'El marcador se abre en su propia ventana en ese fotograma exacto, listo para anotarlo.' },
      { title: 'Anotar, presentar y exportar', location: 'Secciones siguientes', action: 'Dibuja sobre el clip o el marcador, sigue jugadores, crea una presentación y exporta un informe cuando necesites imágenes fijas o los datos de los clips.', result: 'Cada uno de estos pasos tiene su propia sección y su vídeo más abajo.' },
    ],
  },
  installation: {
    title: 'Instalar y ejecutar',
    paragraphs: [
      'Descarga el DMG para Mac o el instalador de Windows desde las [versiones de GitHub](https://github.com/PatrickJYKang/annotate/releases/latest). En macOS, abre el DMG y arrastra Annotate a Aplicaciones. En Windows, ejecuta el instalador y abre Annotate desde el acceso directo del escritorio. Las versiones están pensadas para Mac con Apple Silicon y macOS 14 o posterior, y para Windows 10/11 x64.',
      'Son versiones de evaluación sin firmar, aunque GitHub las marque como «Latest». El sistema puede pedir autorización; no desactives sus protecciones de seguridad. Python, las herramientas de vídeo y los modelos van incluidos. No hace falta terminal ni un navegador aparte. Los servicios se inician y se detienen con la aplicación; el primer inicio puede tardar más mientras se cargan las bibliotecas.',
      'Los registros de los servicios están en `~/Library/Application Support/Annotate/logs/services.log` en macOS y en `%APPDATA%\\Annotate\\logs\\services.log` en Windows. Los editores de clips y de marcadores se abren en ventanas separadas.',
      'El desarrollo con navegador sigue siendo posible con Chrome, Edge, Brave, Arc o Chromium; Safari y Firefox no pueden conceder el acceso necesario a la carpeta del proyecto. El antiguo instalador para navegador y sus instrucciones están en la carpeta [legacy/browser-install](https://github.com/PatrickJYKang/annotate/tree/main/legacy/browser-install) del repositorio.',
    ],
  },
  capture: {
    title: 'Capturar y etiquetar clips',
    paragraphs: [
      'El panel de etiquetado es una superficie de trabajo fija, no un menú. Haz clic una vez en una casilla para iniciar un clip y otra vez en la misma casilla para terminarlo. Una casilla que está grabando muestra un punto rojo y el fotograma de inicio, y el clip en curso aparece en la línea de tiempo antes de terminarlo. Los clips de distintos tipos pueden solaparse.',
      'Los modificadores añaden detalles estructurados a la captura iniciada más recientemente, así que elígelos mientras esa captura está en curso. Su disponibilidad cambia según la casilla, pero el panel no se mueve. No hay margen automático antes ni después: los fotogramas en los que haces clic son los límites del clip.',
      'Haz clic en un clip de la línea de tiempo o de la lista para seleccionarlo e ir a su inicio. Con el vídeo en pausa, elige **Reetiquetar selección** y después los modificadores y la nueva casilla; el clip conserva sus fotogramas y pasa al nuevo grupo de la lista. También puedes arrastrar un clip a otro grupo. **Abrir editor** abre el clip, o lo muestra si ya está abierto, en una ventana separada.',
      'La línea de tiempo de captura separa los grupos en carriles y coloca los solapamientos en subcarriles. Haz clic o arrastra para desplazarte, desplázate en horizontal para avanzar en el tiempo y usa el control de zoom para pasar del detalle fotograma a fotograma al partido completo. Un desplazamiento manual pausa durante cinco segundos el seguimiento automático del cabezal.',
      'El panel integrado sigue el idioma elegido en el encabezado. Los paneles personalizados conservan sus propias etiquetas. Cambiar de idioma no renombra los clips guardados ni cancela las capturas en curso.',
    ],
  },
  clipEditor: {
    title: 'Editar un clip',
    paragraphs: [
      'El editor de clips reúne el vídeo original, los objetos tácticos animados, un inspector de propiedades y una línea de tiempo de fotogramas clave a nivel de fotograma. La reproducción nunca sale de los límites actuales del clip.',
      'Al dibujar un objeto se crea su primer fotograma clave de posición en el fotograma actual. Avanza con los botones de fotograma o haz clic en la línea de tiempo para ir a otro fotograma y allí mueve, cambia de tamaño o gira el objeto: Annotate añade un fotograma clave e interpola entre ellos. Haz clic en un fotograma clave para volver a su fotograma; los cambios que hagas allí modifican ese fotograma clave en lugar de añadir otro.',
      'El color, el grosor de línea, la opacidad del relleno, el patrón, el nombre y las demás propiedades de estilo pertenecen al objeto entero y se aplican en todos los fotogramas. Con **Seleccionar**, haz clic en un objeto o arrastra sobre una zona vacía para seleccionar con un rectángulo. Mayús-clic añade objetos, en el vídeo o en la lista, y los cambios del inspector se aplican entonces a todos. Cmd-clic en macOS o Ctrl-clic en Windows quita objetos. **Fusionar objetos** está disponible para objetos del mismo tipo cuyos fotogramas clave de posición no se solapan.',
    ],
    trimTitle: 'Recortar un clip',
    trim: 'Elige **Recortar** y arrastra cualquiera de los tiradores hacia dentro. El resumen indica cuántos marcadores, fotogramas clave y objetos quitaría el recorte. **Aplicar recorte** confirma los nuevos límites y **Cancelar** los deja como estaban. **Deshacer recorte** restaura los límites anteriores mientras no hagas otro cambio en el clip. Recortar solo acorta un clip; no puede ampliarlo más allá de sus límites originales.',
    keyframeTitle: 'Reglas de los fotogramas clave',
    keyframeRules: [
      'Los fotogramas clave de posición coinciden con fotogramas exactos del vídeo de origen.',
      'Los fotogramas clave manuales y de corrección se pueden arrastrar en horizontal; los del seguimiento son fijos.',
      'Supr elimina los fotogramas clave seleccionados. Mayús+Supr elimina los objetos seleccionados.',
      'Un objeto debe conservar al menos un fotograma clave de posición.',
      'El seguimiento gestiona los límites de mostrar y ocultar sin cambiar la posición. No hay controles manuales para mostrar u ocultar.',
    ],
  },
  tracking: {
    title: 'Seguir a un jugador y corregir errores',
    steps: [
      'Ve a un fotograma claro y elige **Seguir**. Aparecen resaltados provisionales sobre los jugadores detectados.',
      'Selecciona el resaltado provisional del jugador correcto y elige **Iniciar**. Elige **Detener** si solo necesitas un fotograma manual.',
      'El vídeo, el resaltado y la línea de tiempo avanzan a medida que llegan los fotogramas seguidos. La vista previa puede saltarse fotogramas si la decodificación se retrasa, sin perder fotogramas clave. Los marcadores no interrumpen el seguimiento.',
      'Elige **Detener** cuando tengas suficiente. El cabezal vuelve al inicio del seguimiento para que puedas reproducir el resultado.',
    ],
    correctTitle: 'Corregir un seguimiento',
    correct: [
      'Cuando se pierde la continuidad, el resaltado seguido se oculta y vuelven los candidatos provisionales. Selecciona el candidato correcto y elige **Continuar**; Annotate rellena el hueco y sigue. Si el jugador correcto no se detecta en ese fotograma, avanza de fotograma en fotograma hasta que se detecte y continúa. A veces hay que hacerlo varias veces.',
      'Si el seguimiento ha pasado al jugador equivocado, reproduce hasta el cambio, retrocede al último fotograma correcto y elige **Repetir seguimiento desde aquí**. Selecciona al jugador correcto y continúa. **Listo** sustituye el final del seguimiento anterior; **Cancelar** conserva el original.',
      'El seguimiento usa coordenadas de imagen y no necesita homografía. Los identificadores del seguimiento indican continuidad, no la identidad de un jugador, así que cuenta con corregir seguimientos en solapamientos, cambios de plano y cuando los jugadores salen del encuadre.',
    ],
    namesTitle: 'Nombrar jugadores y unir formas',
    names: [
      'Selecciona un resaltado y escribe el nombre del jugador en **Nombre**. Marca **Mostrar nombre** para verlo en el vídeo y ajusta **Tamaño del texto** si hace falta. El nombre también identifica el objeto en la línea de tiempo.',
      '**Flecha**, **Pase bombeado**, **Sombra defensiva** y **Polígono** pueden unirse a los resaltados. Con **Flecha**, haz clic en un resaltado y luego en otro: los dos extremos quedan unidos, y la flecha sigue a los jugadores durante el movimiento sin volver a dibujarla.',
    ],
  },
  pins: {
    title: 'Marcadores y animaciones',
    paragraphs: [
      'Un marcador señala un fotograma exacto dentro de un clip. Elige **Añadir marcador** en el editor de clips para abrir el marcador en su propia ventana, en ese fotograma. El editor de marcadores usa las mismas herramientas de dibujo que el editor de clips, y una flecha trazada de un resaltado a otro queda unida a ambos. Elige **Guardar** y después **Cerrar marcador** para volver al clip.',
      'Mantén ← o → para ver hasta cinco segundos de vídeo alrededor del marcador; las anotaciones se ocultan y la edición se bloquea fuera del fotograma del marcador. Espacio vuelve al fotograma editable. Un marcador también puede tener varios conjuntos de anotaciones con nombre cuando un mismo momento admite otras explicaciones, e **Importar al clip** copia el conjunto activo en el clip, en el fotograma del marcador.',
    ],
    animateTitle: 'Animar un marcador',
    animate: [
      'Abre **Animaciones** en el editor de marcadores, selecciona una forma y elige **Añadir**. Cada paso tiene un efecto (Aparecer, Desvanecer, Crecer o Barrido) y un inicio: Al hacer clic, Con la anterior o Después de la anterior, con retraso y duración ajustables. Por defecto: Desvanecer, Al hacer clic. Las formas sin paso se muestran desde el principio. **Vista previa** y **Siguiente** recorren la secuencia.',
      'Cuando un clip llega a un marcador con animaciones, la reproducción se detiene en el marcador con las formas animadas ocultas. **Reproducir**, Espacio o un clic en el vídeo ejecuta cada paso de clic, y el siguiente clic después del último paso reanuda el clip.',
    ],
  },
  homography: {
    title: 'Dibujar sobre el campo',
    paragraphs: [
      'Para dibujar sobre el propio campo, el clip necesita una homografía. Elige **Calcular H**. La barra de progreso muestra la carga de los modelos y después la calibración de fotogramas de muestra a lo largo del clip; el primer cálculo tras iniciar la aplicación tarda más. **Cancelar** se detiene sin sustituir un resultado existente. Los resultados se guardan en caché, y **Volver a calcular H** los sustituye.',
      '**Mostrar H** superpone la cuadrícula del campo para compararla con las líneas. Cuando hay una homografía, **Rectángulo** y **Círculo** dibujan sobre el campo (**Dibujo: campo**): toman la perspectiva del campo, sus tiradores se mueven sobre el campo y permanecen en la misma zona de césped cuando la cámara se mueve. Las formas dibujadas en coordenadas de imagen, en cambio, quedan fijas en pantalla.',
      '**Eliminar H** quita la homografía y vuelve a dibujar en coordenadas de imagen. La calibración de un marcador ofrece el mismo cálculo automático y, como alternativa, **H manual** para un solo fotograma. El seguimiento no necesita homografía.',
    ],
  },
  presentations: {
    title: 'Crear y reproducir una presentación',
    paragraphs: [
      'Crea una presentación desde la página del proyecto: escribe un nombre, elige **Crear** y después **Abrir**. El espacio de edición tiene un explorador de recursos, una vista previa, una fila horizontal de diapositivas y un inspector.',
      'Haz clic en un recurso para previsualizarlo; no se añade nada hasta que lo arrastres a la presentación. Despliega los marcadores de un clip para arrastrar uno como diapositiva propia. Usa **Añadir título** para títulos, secciones o separadores, y arrastra las miniaturas para reordenarlas. Selecciona una diapositiva de clip para elegir en qué marcadores se pausa.',
      '**Presentar** oculta la interfaz de edición y ocupa toda la ventana. Las diapositivas de clip reproducen el vídeo original con sus anotaciones animadas y se pausan en los marcadores elegidos; los clics muestran los pasos de animación antes de que el clip siga o la presentación avance. **Corte** pasa directamente a la siguiente diapositiva, y **Vídeo del partido** está disponible entre marcadores del mismo vídeo en orden cronológico.',
    ],
  },
  exportRecovery: {
    title: 'Exportar, recuperar y revisar',
    paragraphs: [
      '**Exportar informe…** en la página del proyecto escribe `clips.csv`, `clips.json` y una imagen PNG a la resolución del vídeo por cada conjunto de anotaciones de marcador, dentro de la carpeta del proyecto en `exports/report/`. Los PNG muestran la anotación completa, no un instante de una animación.',
      'Para quitar un clip, selecciónalo en el reproductor de captura y elige **Eliminar clip**. Los clips, marcadores y conjuntos de anotaciones eliminados se copian primero en `.trash/`; usa enseguida **Deshacer eliminación** para restaurar uno. **Vaciar papelera** borra definitivamente los datos de recuperación guardados.',
      'Para quitar un vídeo, usa **Eliminar** junto a él en la página del proyecto y confirma con **Eliminar vídeo y clips**. Esto borra definitivamente la copia del vídeo en el proyecto y todos sus clips, marcadores y conjuntos de anotaciones. El archivo original y las presentaciones no cambian; las diapositivas afectadas indican que falta su origen. La eliminación de un vídeo no se puede deshacer.',
      'El informe de integridad de la página del proyecto enumera los medios que faltan, los documentos ilegibles y las referencias de presentación sin resolver. Sirve para diagnosticar: Annotate no intenta adivinar cómo reescribir tu trabajo. Para tenerlo todo a salvo, haz una copia de seguridad de toda la carpeta del proyecto.',
    ],
  },
  workspaceMap: {
    title: 'Espacios de trabajo',
    headings: ['Espacio', 'Para qué sirve', 'Resultado principal'],
    rows: [
      ['Página del proyecto', 'Crear o abrir proyectos, importar vídeo, editar la información del partido, gestionar presentaciones, exportar y revisar la integridad.', 'Configuración del proyecto e informes'],
      ['Reproductor de captura', 'Ver un vídeo completo y etiquetar jugadas, que pueden solaparse, con el panel fijo.', 'Clips'],
      ['Editor de clips', 'Animar objetos tácticos, seguir jugadores, calcular la homografía, recortar y añadir marcadores.', 'Anotaciones de clip y marcadores'],
      ['Editor de marcadores', 'Crear uno o varios conjuntos de anotaciones y secuencias de animación en un fotograma exacto.', 'Documentos de anotación'],
      ['Editor de presentaciones', 'Ordenar clips, marcadores y títulos en una secuencia.', 'Presentación'],
      ['Modo presentación', 'Reproducir la secuencia sin los controles de edición.', 'Reproducción a pantalla completa'],
      ['Información del partido', 'Mantener equipos, jugadores, entrenadores, marcador, competición, estadio y otros datos del partido.', 'Metadatos del proyecto'],
    ],
  },
  drawingTools: {
    title: 'Herramientas de dibujo y coordenadas',
    headings: ['Herramienta', 'Coordenadas', 'Comportamiento'],
    rows: [
      ['Seleccionar', 'Imagen o campo', 'Seleccionar, mover, cambiar de tamaño, girar o seleccionar con un rectángulo. Mayús-clic añade a la selección.'],
      ['Rectángulo', 'Imagen o campo', 'Una zona rectangular. Con Dibujo: campo queda fija al plano del campo cuando la cámara se mueve.'],
      ['Círculo', 'Imagen o campo', 'Una zona elíptica con tiradores de tamaño y giro. En modo campo se comporta como Rectángulo.'],
      ['Resaltado', 'Imagen', 'Un marcador de jugador. Se puede nombrar, seguir y usar como ancla de formas unidas.'],
      ['Sombra defensiva', 'Imagen', 'Una sombra de cobertura defensiva con tiradores de radio, dirección y apertura.'],
      ['Flecha', 'Imagen', 'Una acción con dirección. Cada extremo puede unirse a un resaltado.'],
      ['Pase bombeado', 'Imagen', 'Una trayectoria de pase curva que se une a los resaltados igual que Flecha.'],
      ['Polígono', 'Imagen', 'Una zona cerrada o una línea abierta. Cada vértice puede unirse a un resaltado.'],
      ['Texto', 'Imagen', 'Texto explicativo fijo. El estilo pertenece al objeto, no a los fotogramas clave.'],
    ],
    note: 'Flecha, Pase bombeado, Sombra defensiva y cada vértice de un Polígono pueden unirse a los resaltados. Una forma unida sigue a su resaltado, tanto si se mueve a mano como por seguimiento. Solo Rectángulo y Círculo usan coordenadas de campo; las demás herramientas usan coordenadas de imagen.',
  },
  keyboard: {
    title: 'Atajos de teclado',
    headings: ['Contexto', 'Atajo', 'Acción'],
    rows: [
      ['Captura', 'Atajo del panel', 'Iniciar o terminar el clip o el modificador asignado.'],
      ['Captura', 'Esc', 'Cancelar el reetiquetado o la última captura iniciada.'],
      ['Captura', 'Supr / Retroceso', 'Mover el clip seleccionado a la papelera del proyecto.'],
      ['Editor de clips', 'Espacio', 'Reproducir, pausar, ejecutar una animación de marcador o seguir después de un marcador.'],
      ['Editor de clips', '← / →', 'Avanzar o retroceder exactamente un fotograma del vídeo de origen.'],
      ['Editor de clips', 'K', 'Añadir o sustituir un fotograma clave de posición en el fotograma actual.'],
      ['Editor de clips', 'Supr / Retroceso', 'Eliminar el fotograma clave seleccionado.'],
      ['Editor de clips', 'Mayús + Supr / Retroceso', 'Eliminar el objeto seleccionado.'],
      ['Editor de clips', 'Cmd/Ctrl + Z', 'Deshacer el último cambio.'],
      ['Editor de clips', 'Cmd/Ctrl + Mayús + Z', 'Rehacer el último cambio. Ctrl + Y también funciona.'],
      ['Editor de clips o de marcadores', 'Intro', 'Terminar un polígono cerrado.'],
      ['Editor de clips o de marcadores', 'Mayús + Intro', 'Terminar una línea de polígono abierta.'],
      ['Editor de marcadores', 'Mantener ← / →', 'Ver hasta cinco segundos alrededor del marcador.'],
      ['Editor de marcadores', 'Espacio', 'Volver al fotograma editable del marcador.'],
      ['Modo presentación', '← / →', 'Retroceder, ejecutar la siguiente animación o avanzar.'],
      ['Modo presentación', 'Espacio / clic', 'Ejecutar la siguiente animación o reanudar un clip en pausa.'],
      ['Modo presentación', 'Esc', 'Salir de la presentación a pantalla completa.'],
    ],
    note: 'Los atajos se ignoran cuando el foco está en un campo de texto, un área de texto o un desplegable.',
  },
  glossary: {
    title: 'Glosario',
    entries: [
      ['Conjunto de anotaciones', 'Una explicación sobre un fotograma fijo, guardada por separado y asociada a un marcador. Un marcador puede tener varios conjuntos alternativos.'],
      ['Panel', 'La disposición fija de botones de captura y modificadores que se usa para etiquetar jugadas mientras se ve el vídeo.'],
      ['Clip', 'Una jugada delimitada por fotogramas. Los clips pueden solaparse y siguen siendo independientes aunque usen el mismo vídeo.'],
      ['Modo de coordenadas', 'El espacio en el que se guarda la geometría de un objeto: píxeles de la imagen o coordenadas de campo proyectadas mediante la homografía.'],
      ['Modificador', 'Información estructurada adicional asociada a un clip, como el resultado o un detalle de la fase.'],
      ['Homografía', 'Una correspondencia, fotograma a fotograma, entre la imagen visible y el plano del campo.'],
      ['Fotograma clave', 'Un fotograma exacto del vídeo de origen en el que un objeto animado guarda su geometría. El seguimiento también registra marcas automáticas de parada o pérdida; no hay controles manuales para mostrar u ocultar.'],
      ['Objeto', 'Una forma de la capa animada del clip, como un resaltado, una flecha, un polígono o un texto.'],
      ['Marcador', 'Un fotograma exacto e importante dentro de un clip. Los marcadores contienen conjuntos de anotaciones sobre fotogramas fijos y pueden pausar la reproducción del clip.'],
      ['Presentación', 'Una secuencia ordenada de clips, marcadores y títulos, con ajustes de reproducción y transición.'],
      ['Fotograma de origen', 'El número de fotograma absoluto en un vídeo importado. Annotate usa fotogramas en lugar de marcas de tiempo aproximadas.'],
      ['Etiqueta', 'La clasificación principal del panel que describe lo que representa un clip capturado.'],
      ['Seguimiento', 'El seguimiento automático de un jugador, que crea los fotogramas clave de posición de un resaltado. Una corrección manual resuelve pérdidas y cambios de jugador.'],
      ['Fotograma clave de visibilidad', 'Un límite de mostrar u ocultar gestionado por el seguimiento para un objeto animado. No guarda posición; no hay controles manuales para mostrar u ocultar.'],
    ],
  },
  projectFiles: {
    title: 'Archivos del proyecto y copias de seguridad',
    paragraphs: [
      'Un proyecto es una carpeta normal. Su manifiesto es `project.json`; los medios de origen están en `media/`; los clips y sus documentos de anotación están en `analysis/`; las presentaciones, exportaciones, cachés y la papelera tienen sus propias carpetas.',
      'No cambies el nombre ni muevas archivos internos mientras un proyecto está abierto. Para hacer una copia de seguridad o mover un proyecto, ciérralo y copia la carpeta completa. Los vídeos se copian en el proyecto, así que durante la importación necesitas espacio para el archivo de origen y para su copia.',
      'Los proyectos de Annotate 0.2 usan el modelo `project.v2` y no son compatibles con Annotate 0.1. Conserva una instalación de 0.1 para los proyectos antiguos.',
    ],
  },
  troubleshooting: {
    title: 'Solución de problemas',
    entries: [
      ['No se abre una carpeta de proyecto', 'Comprueba que la carpeta se puede escribir y contiene `project.json`. En el navegador, Chromium también necesita permiso sobre la carpeta; Safari y Firefox no ofrecen la API necesaria.'],
      ['El servicio no está disponible', 'Cierra y vuelve a abrir Annotate. Guarda el mensaje de error y el registro de los servicios; consulta Instalar y ejecutar para su ubicación. La aplicación de escritorio elige sus propios puertos locales.'],
      ['Un marcador no se abre', 'En la aplicación de escritorio, busca una ventana de marcador ya abierta; volver a abrir el mismo marcador la muestra. En un navegador, permite las ventanas emergentes para la dirección de la aplicación y vuelve a intentarlo.'],
      ['El primer seguimiento no se carga', 'Las versiones de escritorio incluyen el modelo YOLO. Reinicia y comunica el error con el registro de los servicios. En el desarrollo con navegador, el modelo puede descargarse la primera vez.'],
      ['La homografía no está disponible', 'Las versiones de escritorio incluyen PnLCalib y sus pesos. Reinicia Annotate y, si continúa, comunica el error de inicio con el registro de los servicios.'],
      ['La importación de vídeo es lenta', 'Un MP4 H.264 compatible con frecuencia de fotogramas constante se conserva o se reempaqueta. Otros códecs y las frecuencias variables requieren una transcodificación completa. Cancelar elimina de forma segura los archivos temporales.'],
      ['El seguimiento cambia de jugador en un solapamiento', 'Detente en el último fotograma fiable, elige **Repetir seguimiento desde aquí**, selecciona el jugador provisional correcto y continúa. **Cancelar** conserva el final original.'],
      ['El informe de integridad indica que falta algo', 'Restáuralo desde `.trash` si es posible, o quita la referencia rota de la presentación. Annotate indica la ruta en lugar de reescribir tu trabajo sin avisar.'],
    ],
  },
  onThisPage: [
    ['videos', 'Tutoriales en vídeo'],
    ['first-project', 'Primer proyecto'],
    ['capture', 'Captura'],
    ['clip-editor', 'Editor de clips'],
    ['tracking', 'Seguimiento'],
    ['pins', 'Marcadores'],
    ['homography', 'Dibujo sobre el campo'],
    ['presentations', 'Presentaciones'],
    ['export-recovery', 'Exportar'],
    ['keyboard', 'Atajos'],
    ['glossary', 'Glosario'],
  ],
};
