import type { GuideContent } from './types';

export const fr: GuideContent = {
  ui: {
    searchLabel: 'Rechercher dans le guide',
    searchPlaceholder: 'Suivi, repères, raccourcis…',
    navigationLabel: 'Guide d’utilisation',
    mobileNavigationLabel: 'Guide d’utilisation (mobile)',
    browseSections: 'Parcourir les sections',
    resultCount: (count) => `${count} résultat${count === 1 ? '' : 's'}`,
    noResults: 'Aucune section ne correspond à cette recherche.',
    onThisPage: 'Sur cette page',
    video: 'VIDÉO',
    videoComingSoon: 'Vidéo bientôt disponible.',
    englishRecording: ' (Enregistrement en anglais.)',
    result: 'Résultat :',
  },
  title: 'Guide d’utilisation d’Annotate',
  lede: 'Documentation sur la création de projets, la capture de clips, l’annotation, le suivi, les repères, les présentations, l’export et le stockage des projets.',
  groups: [
    {
      label: 'Pour commencer',
      links: [
        { id: 'orientation', label: 'Vue d’ensemble', summary: 'Structure d’un projet et modèle clip, repère et présentation.', keywords: 'présentation générale introduction modèle' },
        { id: 'videos', label: 'Tutoriels vidéo', summary: 'Douze courts enregistrements des principaux usages.', keywords: 'vidéo tutoriel démonstration regarder enregistrement' },
        { id: 'first-project', label: 'Premier projet', summary: 'D’un projet vide à un clip avec un repère.', keywords: 'création importer démonstration' },
        { id: 'installation', label: 'Installer et lancer', summary: 'Téléchargements, lancement et services locaux.', keywords: 'installation lancement mac windows bureau navigateur' },
      ],
    },
    {
      label: 'Méthodes de travail',
      links: [
        { id: 'capture', label: 'Capturer et coder', summary: 'Transformer des phases de jeu en clips qui peuvent se chevaucher.', keywords: 'tableau modificateur frise codage recoder' },
        { id: 'clip-editor', label: 'Modifier un clip', summary: 'Dessiner et animer des formes, et rogner le clip.', keywords: 'image clé frise rectangle cercle flèche polygone rogner' },
        { id: 'tracking', label: 'Suivre et corriger', summary: 'Suivre des joueurs, corriger les erreurs et nommer les surlignages.', keywords: 'suivi joueur surlignage chevauchement nom étiquette' },
        { id: 'pins', label: 'Repères et animations', summary: 'Annoter des images précises et révéler les annotations étape par étape.', keywords: 'image fixe jeu d’annotations animation' },
        { id: 'homography', label: 'Dessiner sur le terrain', summary: 'Homographie, rectangles et cercles sur le terrain.', keywords: 'homographie terrain grille calculer afficher supprimer' },
        { id: 'presentations', label: 'Présentations', summary: 'Créer et lire des séquences de clips, de repères et de titres.', keywords: 'diapositives présenter transition vidéo du match' },
        { id: 'export-recovery', label: 'Export et récupération', summary: 'Rapports, images, corbeille et contrôles d’intégrité.', keywords: 'png csv json sauvegarde restaurer manquant corbeille' },
      ],
    },
    {
      label: 'Référence',
      links: [
        { id: 'workspace-map', label: 'Espaces de travail', summary: 'Où se fait chaque type de travail.', keywords: 'page du projet capture éditeur présentation métadonnées' },
        { id: 'drawing-tools', label: 'Outils de dessin', summary: 'Comportement des outils et systèmes de coordonnées.', keywords: 'sélection surlignage texte style terrain image' },
        { id: 'keyboard', label: 'Raccourcis clavier', summary: 'Touches de lecture, d’édition et de présentation.', keywords: 'raccourcis commandes espace supprimer annuler' },
        { id: 'glossary', label: 'Glossaire', summary: 'Définitions des notions d’Annotate.', keywords: 'termes définitions clip repère image clé' },
        { id: 'project-files', label: 'Fichiers du projet', summary: 'Stockage local et sauvegarde sûre.', keywords: 'dossier projet json médias analyse exports corbeille' },
        { id: 'troubleshooting', label: 'Dépannage', summary: 'Problèmes courants et premières vérifications.', keywords: 'hors ligne fenêtre lent erreur modèle' },
      ],
    },
  ],
  tutorials: {
    'first-project': { title: 'Votre premier projet', description: 'Créer un projet, importer la vidéo d’un match, capturer une possession avec un modificateur, ouvrir l’éditeur de clip et ajouter un repère.' },
    'capture-tagging': { title: 'Capturer et coder une phase de jeu', description: 'Coder un match pendant sa lecture, avec des clips qui se chevauchent et un modificateur, puis recoder un clip et zoomer sur la frise.' },
    'clip-editing': { title: 'Dessiner et animer des formes', description: 'Dessiner un rectangle, le déplacer pour créer des images clés, le redimensionner et le faire pivoter, ajouter un cercle et modifier le style des deux à la fois.' },
    'clip-trimming': { title: 'Rogner un clip', description: 'Faire glisser les deux poignées vers l’intérieur, vérifier le résumé, appliquer le rognage puis l’annuler aussitôt.' },
    'basic-tracking': { title: 'Suivre un joueur', description: 'Choisir un joueur parmi les surlignages provisoires, lancer le suivi, l’arrêter et vérifier le résultat à vitesse normale.' },
    'tracking-correction': { title: 'Corriger un suivi', description: 'Le suivi passe sur le mauvais joueur. Revenir à la dernière image correcte, refaire le suivi, avancer d’une image quand le joueur est perdu, puis continuer.' },
    'tracking-refinements': { title: 'Nommer les joueurs et rattacher une flèche', description: 'Nommer deux surlignages suivis, afficher leurs noms sur la vidéo et rattacher une flèche aux deux pour qu’elle les suive.' },
    'pin-annotation': { title: 'Annoter un repère', description: 'Ajouter un repère, surligner deux joueurs, les relier par une flèche rattachée, changer son style, enregistrer et fermer le repère.' },
    'pin-animations': { title: 'Animer un repère', description: 'Faire apparaître les annotations d’un repère étape par étape, prévisualiser la séquence, puis lire le clip jusqu’au repère.' },
    homography: { title: 'Dessiner sur le terrain', description: 'Calculer l’homographie, vérifier la grille du terrain, dessiner un rectangle sur le terrain et lire un panoramique.' },
    'presentation-authoring': { title: 'Créer et présenter une présentation', description: 'Créer une présentation, y ajouter un clip, un repère et un titre, choisir où le clip s’arrête, puis présenter.' },
    'export-recovery': { title: 'Exporter et récupérer', description: 'Exporter un rapport, retrouver ses fichiers, supprimer un clip puis annuler la suppression, et sauvegarder le dossier du projet.' },
  },
  overview: {
    title: 'Vue d’ensemble',
    paragraphs: [
      'Annotate est une application locale d’analyse vidéo de football. Un projet contient les vidéos importées, les clips capturés, les repères, les données d’annotation, les présentations, les exports, les caches et une corbeille récupérable.',
      'Les annotations de clip sont des objets à images clés affichés sur la vidéo. Les annotations de repère sont des documents rattachés à une image précise de la source et peuvent comporter des animations d’entrée. Le suivi génère les images clés des surlignages, et l’homographie fournit des coordonnées terrain pour les rectangles et les cercles.',
      'Les données sont enregistrées dans le dossier du projet choisi. L’application communique avec un service Python sur le même ordinateur pour l’import vidéo, le suivi, l’homographie et l’export. Les versions de bureau incluent et gèrent ce service ; en développement dans le navigateur, il est lancé séparément.',
    ],
    cards: [
      ['Clip', 'Un intervalle d’images semi-ouvert dans une vidéo importée.'],
      ['Repère', 'Une image précise dans un clip, avec zéro ou plusieurs jeux d’annotations.'],
      ['Présentation', 'Une suite ordonnée de clips, de repères et de titres.'],
    ],
  },
  videos: {
    title: 'Tutoriels vidéo',
    intro: 'Chaque section ci-dessous comprend un court enregistrement de l’application, lu depuis YouTube. Les vidéos sont muettes et sous-titrées, et suivent la langue choisie dans l’en-tête quand un enregistrement existe dans cette langue ; sinon, l’enregistrement anglais s’affiche. Sélectionnez un tutoriel pour y accéder.',
  },
  firstProject: {
    title: 'Premier projet',
    intro: 'La procédure suivante crée un projet, importe la vidéo d’un match, capture un clip et y ajoute un repère. Le dessin, le suivi, les présentations et l’export sont traités dans les sections suivantes.',
    steps: [
      { title: 'Créer le projet', location: 'Écran d’accueil', action: 'Choisissez **Créer un projet**, saisissez les informations du match que vous connaissez et choisissez un dossier parent.', result: 'Annotate crée un dossier de projet ordinaire et ouvre la page du projet.' },
      { title: 'Importer une vidéo', location: 'Page du projet · Vidéos', action: 'Choisissez **Importer une vidéo…** et sélectionnez le fichier du match. Laissez Annotate ouvert pendant la préparation du média.', result: 'La vidéo apparaît dans le projet avec sa fréquence d’images et sa résolution d’origine.' },
      { title: 'Capturer un clip', location: 'Lecteur de capture', action: 'Ouvrez le lecteur de capture, lancez la lecture, cliquez sur une tuile du tableau à la première image de la phase de jeu, ajoutez des modificateurs, puis cliquez à nouveau sur la même tuile à la dernière image.', result: 'Un clip codé apparaît sur la frise et dans la liste des clips.' },
      { title: 'Ouvrir le clip et ajouter un repère', location: 'Éditeur de clip', action: 'Sélectionnez le clip et choisissez **Ouvrir l’éditeur**. Allez à l’image à expliquer et choisissez **Ajouter un repère**.', result: 'Le repère s’ouvre dans sa propre fenêtre, exactement sur cette image, prêt à être annoté.' },
      { title: 'Annoter, présenter et exporter', location: 'Sections suivantes', action: 'Dessinez sur le clip ou le repère, suivez des joueurs, créez une présentation et exportez un rapport quand vous avez besoin d’images fixes ou des données des clips.', result: 'Chacune de ces étapes a sa propre section et sa vidéo plus bas.' },
    ],
  },
  installation: {
    title: 'Installer et lancer',
    paragraphs: [
      'Téléchargez le DMG pour Mac ou l’installeur Windows depuis les [versions GitHub](https://github.com/PatrickJYKang/annotate/releases/latest). Sur macOS, ouvrez le DMG et faites glisser Annotate dans Applications. Sur Windows, lancez l’installeur puis ouvrez Annotate depuis son raccourci sur le bureau. Les versions ciblent les Mac Apple Silicon sous macOS 14 ou plus récent, et Windows 10/11 x64.',
      'Ce sont des versions d’évaluation non signées, même lorsque GitHub indique « Latest ». Le système peut demander une autorisation ; ne désactivez pas ses protections. Python, les outils vidéo et les modèles sont inclus. Aucun terminal ni navigateur séparé n’est nécessaire. Les services démarrent et s’arrêtent avec l’application ; le premier lancement peut être plus long le temps que les bibliothèques s’initialisent.',
      'Les journaux des services se trouvent dans `~/Library/Application Support/Annotate/logs/services.log` sur macOS et `%APPDATA%\\Annotate\\logs\\services.log` sur Windows. Les éditeurs de clip et de repère s’ouvrent dans des fenêtres séparées.',
      'Le développement dans le navigateur reste possible avec Chrome, Edge, Brave, Arc ou Chromium ; Safari et Firefox ne peuvent pas accorder l’accès nécessaire au dossier du projet. L’ancien installeur pour navigateur et ses instructions se trouvent dans le dossier [legacy/browser-install](https://github.com/PatrickJYKang/annotate/tree/main/legacy/browser-install) du dépôt.',
    ],
  },
  capture: {
    title: 'Capturer et coder des clips',
    paragraphs: [
      'Le tableau de codage est une surface de travail fixe, pas un menu. Cliquez une fois sur une tuile pour démarrer un clip, puis à nouveau sur la même tuile pour le terminer. Une tuile en cours d’enregistrement affiche un point rouge et l’image de départ, et le clip en cours apparaît sur la frise avant d’être terminé. Des clips de types différents peuvent se chevaucher.',
      'Les modificateurs ajoutent des détails structurés à la capture démarrée en dernier : choisissez-les pendant que cette capture est en cours. Leur disponibilité dépend de la tuile, mais le tableau reste en place. Il n’y a pas de marge automatique avant ou après : les images où vous cliquez deviennent les limites du clip.',
      'Cliquez sur un clip dans la frise ou la liste pour le sélectionner et aller à son début. En pause, choisissez **Recoder la sélection**, puis les modificateurs et la nouvelle tuile ; le clip garde ses images et passe dans le nouveau groupe de la liste. Vous pouvez aussi faire glisser un clip sur un autre groupe. **Ouvrir l’éditeur** ouvre le clip, ou l’affiche s’il est déjà ouvert, dans une fenêtre séparée.',
      'La frise de capture sépare les groupes en pistes et range les chevauchements dans des sous-pistes. Cliquez ou faites glisser pour vous déplacer, faites défiler horizontalement pour avancer dans le temps et utilisez le curseur de zoom pour passer de l’image près au match entier. Un défilement manuel suspend le suivi automatique de la tête de lecture pendant cinq secondes.',
      'Le tableau intégré suit la langue choisie dans l’en-tête. Les tableaux personnalisés gardent leurs propres libellés. Changer de langue ne renomme pas les clips enregistrés et n’annule pas les captures en cours.',
    ],
  },
  clipEditor: {
    title: 'Modifier un clip',
    paragraphs: [
      'L’éditeur de clip réunit la vidéo d’origine, les objets tactiques animés, un inspecteur de propriétés et une frise d’images clés à l’image près. La lecture ne sort jamais des limites actuelles du clip.',
      'Dessiner un objet crée sa première image clé de position à l’image courante. Avancez avec les boutons image par image ou cliquez sur la frise pour aller à une autre image, puis déplacez, redimensionnez ou faites pivoter l’objet : Annotate ajoute une image clé et interpole entre elles. Cliquez sur une image clé pour revenir à son image ; les modifications faites là changent cette image clé au lieu d’en ajouter une.',
      'La couleur, la largeur du trait, l’opacité du remplissage, le motif, le nom et les autres propriétés de style appartiennent à l’objet entier et s’appliquent à toutes les images. Avec **Sélection**, cliquez sur un objet ou faites glisser sur une zone vide pour une sélection rectangulaire. Maj-clic ajoute des objets, dans la vidéo comme dans la liste, et les changements dans l’inspecteur s’appliquent alors à tous. Cmd-clic sur macOS ou Ctrl-clic sur Windows retire des objets. **Fusionner les objets** est disponible pour des objets du même type dont les images clés de position ne se chevauchent pas.',
    ],
    trimTitle: 'Rogner un clip',
    trim: 'Choisissez **Rogner** et faites glisser l’une ou l’autre poignée vers l’intérieur. Le résumé indique combien de repères, d’images clés et d’objets le rognage retirerait. **Appliquer** valide les nouvelles limites et **Annuler** les laisse intactes. **Annuler le rognage** rétablit les limites précédentes tant qu’aucune autre modification n’a été faite. Le rognage ne fait que raccourcir un clip ; il ne peut pas l’étendre au-delà de ses limites d’origine.',
    keyframeTitle: 'Règles des images clés',
    keyframeRules: [
      'Les images clés de position correspondent à des images exactes de la vidéo source.',
      'Les images clés manuelles et de correction peuvent être déplacées horizontalement ; celles du suivi sont fixes.',
      'Suppr retire les images clés sélectionnées. Maj+Suppr retire les objets sélectionnés.',
      'Un objet doit conserver au moins une image clé de position.',
      'Le suivi gère les limites d’affichage et de masquage sans changer la position. Il n’existe pas de commande manuelle pour afficher ou masquer.',
    ],
  },
  tracking: {
    title: 'Suivre un joueur et corriger les erreurs',
    steps: [
      'Allez à une image nette et choisissez **Suivre**. Des surlignages provisoires apparaissent sur les joueurs détectés.',
      'Sélectionnez le surlignage provisoire du bon joueur, puis choisissez **Démarrer**. Choisissez plutôt **Arrêter** si une seule image manuelle suffit.',
      'La vidéo, le surlignage et la frise suivent les images au fur et à mesure du suivi. L’aperçu peut sauter des images si le décodage prend du retard, sans perdre d’images clés. Les repères n’interrompent pas le suivi.',
      'Choisissez **Arrêter** quand vous en avez assez. La tête de lecture revient au début du suivi pour que vous puissiez lire le résultat.',
    ],
    correctTitle: 'Corriger un suivi',
    correct: [
      'Quand la continuité est perdue, le surlignage suivi se masque et les candidats provisoires réapparaissent. Sélectionnez le bon candidat et choisissez **Continuer** ; Annotate comble l’intervalle et reprend. Si le bon joueur n’est pas détecté sur cette image, avancez image par image jusqu’à ce qu’il le soit, puis continuez. Il faut parfois le faire plusieurs fois.',
      'Si le suivi est passé sur le mauvais joueur, relisez jusqu’au changement, revenez à la dernière image correcte et choisissez **Refaire le suivi d’ici**. Sélectionnez le bon joueur et continuez. **Terminer** remplace la fin de l’ancien suivi ; **Annuler** conserve l’original.',
      'Le suivi utilise les coordonnées de l’image et ne nécessite pas d’homographie. Les identifiants du suivi indiquent une continuité, pas l’identité d’un joueur : attendez-vous à corriger des suivis lors des chevauchements, des changements de plan et des sorties du cadre.',
    ],
    namesTitle: 'Nommer les joueurs et rattacher des formes',
    names: [
      'Sélectionnez un surlignage et saisissez le nom du joueur dans **Nom**. Cochez **Afficher le nom** pour l’afficher sur la vidéo et ajustez **Taille du texte** si besoin. Le nom sert aussi d’étiquette à l’objet dans la frise.',
      '**Flèche**, **Passe lobée**, **Zone d’ombre** et **Polygone** peuvent se rattacher aux surlignages. Avec **Flèche**, cliquez sur un surlignage puis sur un autre : les deux extrémités sont rattachées, et la flèche suit les joueurs pendant leur déplacement sans être redessinée.',
    ],
  },
  pins: {
    title: 'Repères et animations',
    paragraphs: [
      'Un repère marque une image précise dans un clip. Choisissez **Ajouter un repère** dans l’éditeur de clip pour ouvrir le repère dans sa propre fenêtre, sur cette image. L’éditeur de repère utilise les mêmes outils de dessin que l’éditeur de clip, et une flèche tracée d’un surlignage à un autre reste rattachée aux deux. Choisissez **Enregistrer**, puis **Fermer le repère** pour revenir au clip.',
      'Maintenez ← ou → pour voir jusqu’à cinq secondes de vidéo autour du repère ; les annotations se masquent et l’édition est verrouillée hors de l’image du repère. Espace revient à l’image modifiable. Un repère peut aussi contenir plusieurs jeux d’annotations nommés quand un même moment demande d’autres explications, et **Importer dans le clip** copie le jeu actif dans le clip à l’image du repère.',
    ],
    animateTitle: 'Animer un repère',
    animate: [
      'Ouvrez **Animations** dans l’éditeur de repère, sélectionnez une forme et choisissez **Ajouter**. Chaque étape a un effet (Apparition, Fondu, Agrandissement ou Balayage) et un déclenchement : Au clic, Avec la précédente ou Après la précédente, avec un délai et une durée réglables. Par défaut : Fondu, Au clic. Les formes sans étape sont visibles dès le début. **Aperçu** puis **Suivant** parcourent la séquence.',
      'Quand un clip est lu jusqu’à un repère animé, la lecture s’arrête au repère avec les formes animées masquées. **Lire**, Espace ou un clic sur la vidéo déclenche chaque étape au clic, et le clic suivant après la dernière étape reprend le clip.',
    ],
  },
  homography: {
    title: 'Dessiner sur le terrain',
    paragraphs: [
      'Pour dessiner sur le terrain lui-même, le clip a besoin d’une homographie. Choisissez **Calculer H**. La barre de progression montre le chargement des modèles, puis la calibration d’images échantillons réparties sur tout le clip ; le premier calcul après le démarrage de l’application est plus long. **Annuler** s’arrête sans remplacer un résultat existant. Les résultats sont mis en cache, et **Recalculer H** les remplace.',
      '**Afficher H** superpose la grille du terrain pour la comparer aux lignes. Quand une homographie est disponible, **Rectangle** et **Cercle** dessinent sur le terrain (**Dessin : terrain**) : ils prennent la perspective du terrain, leurs poignées se déplacent sur le terrain, et ils restent sur la même zone de pelouse quand la caméra bouge. Les formes dessinées en coordonnées image restent au contraire fixes à l’écran.',
      '**Supprimer H** retire l’homographie et revient au dessin en coordonnées image. La calibration d’un repère propose le même calcul automatique et, en secours, **H manuelle** pour une seule image. Le suivi n’a pas besoin d’homographie.',
    ],
  },
  presentations: {
    title: 'Créer et lire une présentation',
    paragraphs: [
      'Créez une présentation depuis la page du projet : saisissez un nom, choisissez **Créer**, puis **Ouvrir**. L’espace de création comprend un navigateur de sources, un aperçu, une suite horizontale de diapositives et un inspecteur.',
      'Cliquez sur une source pour la prévisualiser ; rien n’est ajouté tant que vous ne la faites pas glisser dans la présentation. Développez les repères d’un clip pour en faire glisser un comme diapositive. Utilisez **Ajouter un titre** pour les titres, sections ou séparateurs, et faites glisser les miniatures pour les réordonner. Sélectionnez une diapositive de clip pour choisir à quels repères elle s’arrête.',
      '**Présenter** masque l’interface d’édition et occupe toute la fenêtre. Les diapositives de clip lisent la vidéo d’origine avec leurs annotations animées et s’arrêtent aux repères choisis ; les clics révèlent les étapes d’animation avant que le clip reprenne ou que la présentation avance. **Coupe** passe directement à la diapositive suivante, et **Vidéo du match** est disponible entre des repères de la même vidéo dans l’ordre chronologique.',
    ],
  },
  exportRecovery: {
    title: 'Exporter, récupérer et vérifier',
    paragraphs: [
      '**Exporter le rapport…** sur la page du projet écrit `clips.csv`, `clips.json` et une image PNG à la résolution de la vidéo pour chaque jeu d’annotations de repère, dans le dossier du projet sous `exports/report/`. Les PNG montrent l’annotation complète, pas un instant d’une animation.',
      'Pour retirer un clip, sélectionnez-le dans le lecteur de capture et choisissez **Supprimer le clip**. Les clips, repères et jeux d’annotations supprimés sont d’abord copiés dans `.trash/` ; utilisez aussitôt **Annuler la suppression** pour en restaurer un. **Vider la corbeille** efface définitivement les données de récupération conservées.',
      'Pour retirer une vidéo, utilisez **Supprimer** à côté d’elle sur la page du projet et confirmez avec **Supprimer la vidéo et les clips**. Cela supprime définitivement la copie de la vidéo dans le projet ainsi que tous ses clips, repères et jeux d’annotations. Le fichier d’origine et les présentations ne sont pas modifiés ; les diapositives concernées signalent des sources manquantes. La suppression d’une vidéo ne peut pas être annulée.',
      'Le rapport d’intégrité de la page du projet liste les médias manquants, les documents illisibles et les références de présentation non résolues. Il sert au diagnostic : Annotate ne devine pas comment réécrire votre travail. Pour tout protéger, sauvegardez le dossier du projet en entier.',
    ],
  },
  workspaceMap: {
    title: 'Espaces de travail',
    headings: ['Espace', 'Rôle', 'Résultat principal'],
    rows: [
      ['Page du projet', 'Créer ou ouvrir des projets, importer des vidéos, modifier les informations du match, gérer les présentations, exporter et vérifier l’intégrité.', 'Configuration du projet et rapports'],
      ['Lecteur de capture', 'Regarder une vidéo entière et coder des phases de jeu, éventuellement chevauchantes, avec le tableau fixe.', 'Clips'],
      ['Éditeur de clip', 'Animer des objets tactiques, suivre des joueurs, calculer l’homographie, rogner et ajouter des repères.', 'Annotations de clip et repères'],
      ['Éditeur de repère', 'Créer un ou plusieurs jeux d’annotations et des séquences d’animation sur une image précise.', 'Documents d’annotation'],
      ['Éditeur de présentation', 'Organiser clips, repères et titres en une séquence.', 'Présentation'],
      ['Mode présentation', 'Lire la séquence sans les commandes d’édition.', 'Lecture plein écran'],
      ['Informations du match', 'Gérer équipes, joueurs, entraîneurs, score, compétition, stade et autres informations.', 'Métadonnées du projet'],
    ],
  },
  drawingTools: {
    title: 'Outils de dessin et coordonnées',
    headings: ['Outil', 'Coordonnées', 'Comportement'],
    rows: [
      ['Sélection', 'Image ou terrain', 'Sélectionner, déplacer, redimensionner, faire pivoter ou sélectionner au rectangle. Maj-clic ajoute à la sélection.'],
      ['Rectangle', 'Image ou terrain', 'Une zone rectangulaire. En Dessin : terrain, elle reste fixée au plan du terrain quand la caméra bouge.'],
      ['Cercle', 'Image ou terrain', 'Une zone elliptique avec poignées de taille et de rotation. En mode terrain, il se comporte comme Rectangle.'],
      ['Surlignage', 'Image', 'Un marqueur de joueur. Il peut être nommé, suivi et servir d’ancrage aux formes rattachées.'],
      ['Zone d’ombre', 'Image', 'Une ombre de couverture défensive avec poignées de rayon, de direction et d’ouverture.'],
      ['Flèche', 'Image', 'Une action orientée. Chaque extrémité peut se rattacher à un surlignage.'],
      ['Passe lobée', 'Image', 'Une trajectoire de passe courbe, rattachable aux surlignages comme Flèche.'],
      ['Polygone', 'Image', 'Une zone fermée ou une ligne ouverte. Chaque sommet peut se rattacher à un surlignage.'],
      ['Texte', 'Image', 'Un texte explicatif fixe. Le style appartient à l’objet, pas aux images clés.'],
    ],
    note: 'Flèche, Passe lobée, Zone d’ombre et chaque sommet d’un Polygone peuvent se rattacher aux surlignages. Une forme rattachée suit son surlignage, que son mouvement soit manuel ou issu du suivi. Seuls Rectangle et Cercle utilisent les coordonnées terrain ; les autres outils restent en coordonnées image.',
  },
  keyboard: {
    title: 'Raccourcis clavier',
    headings: ['Contexte', 'Raccourci', 'Action'],
    rows: [
      ['Capture', 'Raccourci du tableau', 'Démarrer ou terminer le clip ou le modificateur associé.'],
      ['Capture', 'Échap', 'Annuler le recodage ou la dernière capture démarrée.'],
      ['Capture', 'Suppr / Retour arrière', 'Placer le clip sélectionné dans la corbeille du projet.'],
      ['Éditeur de clip', 'Espace', 'Lire, mettre en pause, déclencher une animation de repère ou reprendre après un repère.'],
      ['Éditeur de clip', '← / →', 'Avancer ou reculer d’exactement une image de la vidéo source.'],
      ['Éditeur de clip', 'K', 'Ajouter ou remplacer une image clé de position à l’image courante.'],
      ['Éditeur de clip', 'Suppr / Retour arrière', 'Supprimer l’image clé sélectionnée.'],
      ['Éditeur de clip', 'Maj + Suppr / Retour arrière', 'Supprimer l’objet sélectionné.'],
      ['Éditeur de clip', 'Cmd/Ctrl + Z', 'Annuler la dernière modification.'],
      ['Éditeur de clip', 'Cmd/Ctrl + Maj + Z', 'Rétablir la dernière modification. Ctrl + Y fonctionne aussi.'],
      ['Éditeur de clip ou de repère', 'Entrée', 'Terminer un polygone fermé.'],
      ['Éditeur de clip ou de repère', 'Maj + Entrée', 'Terminer une ligne de polygone ouverte.'],
      ['Éditeur de repère', 'Maintenir ← / →', 'Voir jusqu’à cinq secondes autour du repère.'],
      ['Éditeur de repère', 'Espace', 'Revenir à l’image modifiable du repère.'],
      ['Mode présentation', '← / →', 'Reculer, déclencher l’animation suivante ou avancer.'],
      ['Mode présentation', 'Espace / clic', 'Déclencher l’animation suivante ou reprendre un clip en pause.'],
      ['Mode présentation', 'Échap', 'Quitter la présentation plein écran.'],
    ],
    note: 'Les raccourcis sont ignorés quand le focus est dans un champ de texte, une zone de texte ou une liste déroulante.',
  },
  glossary: {
    title: 'Glossaire',
    entries: [
      ['Jeu d’annotations', 'Une explication sur image figée, enregistrée séparément et rattachée à un repère. Un repère peut en contenir plusieurs.'],
      ['Tableau', 'La disposition fixe des boutons de capture et des modificateurs utilisée pour coder les phases de jeu pendant le visionnage.'],
      ['Clip', 'Une phase de jeu délimitée par des images. Les clips peuvent se chevaucher et restent indépendants, même sur la même vidéo.'],
      ['Mode de coordonnées', 'L’espace dans lequel la géométrie d’un objet est enregistrée : pixels de l’image ou coordonnées terrain projetées par l’homographie.'],
      ['Modificateur', 'Une information structurée ajoutée à un clip, comme une issue ou un détail de phase.'],
      ['Homographie', 'Une correspondance, image par image, entre l’image visible et le plan du terrain.'],
      ['Image clé', 'Une image exacte de la vidéo source où un objet animé enregistre sa géométrie. Le suivi enregistre aussi des marqueurs automatiques d’arrêt ou de perte ; il n’existe pas de commande manuelle pour afficher ou masquer.'],
      ['Objet', 'Une forme de la couche animée du clip : surlignage, flèche, polygone ou texte, par exemple.'],
      ['Repère', 'Une image importante et précise dans un clip. Les repères portent des jeux d’annotations sur image figée et peuvent arrêter la lecture du clip.'],
      ['Présentation', 'Une suite ordonnée de clips, de repères et de titres, avec des réglages de lecture et de transition.'],
      ['Image source', 'Le numéro d’image absolu dans une vidéo importée. Annotate utilise des images plutôt que des horodatages approximatifs.'],
      ['Code', 'La classification principale du tableau, qui décrit ce que représente un clip capturé.'],
      ['Suivi', 'Le suivi automatique d’un joueur, qui crée les images clés de position d’un surlignage. Une reprise manuelle corrige les pertes et les changements de joueur.'],
      ['Image clé de visibilité', 'Une limite d’affichage ou de masquage gérée par le suivi pour un objet animé. Elle n’enregistre pas de position ; il n’existe pas de commande manuelle pour afficher ou masquer.'],
    ],
  },
  projectFiles: {
    title: 'Fichiers du projet et sauvegardes',
    paragraphs: [
      'Un projet est un dossier ordinaire. Son manifeste est `project.json` ; les médias source sont dans `media/` ; les clips et leurs documents d’annotation sont dans `analysis/` ; les présentations, exports, caches et la corbeille ont leurs propres dossiers.',
      'Ne renommez pas et ne déplacez pas les fichiers internes quand un projet est ouvert. Pour sauvegarder ou déplacer un projet, fermez-le et copiez le dossier entier. Les vidéos sont copiées dans le projet : prévoyez la place pour le fichier source et sa copie pendant l’import.',
      'Les projets Annotate 0.2 utilisent le modèle `project.v2` et ne sont pas compatibles avec Annotate 0.1. Gardez une installation 0.1 pour les anciens projets.',
    ],
  },
  troubleshooting: {
    title: 'Dépannage',
    entries: [
      ['Un dossier de projet ne s’ouvre pas', 'Vérifiez que le dossier est accessible en écriture et contient `project.json`. Dans le navigateur, Chromium doit aussi avoir accès au dossier ; Safari et Firefox ne fournissent pas l’API nécessaire.'],
      ['Le service est hors ligne', 'Quittez puis rouvrez Annotate. Conservez le message d’erreur et le journal des services ; voir Installer et lancer pour leur emplacement. L’application de bureau choisit elle-même ses ports locaux.'],
      ['Un repère ne s’ouvre nulle part', 'Dans l’application de bureau, cherchez une fenêtre de repère déjà ouverte ; rouvrir le même repère l’affiche. Dans un navigateur, autorisez les fenêtres contextuelles pour l’adresse de l’application et réessayez.'],
      ['Le premier suivi ne se charge pas', 'Les versions de bureau incluent le modèle YOLO. Redémarrez et signalez l’erreur avec le journal des services. En développement dans le navigateur, le modèle peut être téléchargé au premier usage.'],
      ['L’homographie n’est pas disponible', 'Les versions de bureau incluent PnLCalib et ses poids. Redémarrez Annotate et, si le problème persiste, signalez l’erreur de démarrage avec le journal des services.'],
      ['L’import vidéo est lent', 'Une vidéo H.264 MP4 compatible à fréquence d’images constante est conservée ou réencapsulée. Les autres codecs et les fréquences variables nécessitent un transcodage complet. Annuler supprime proprement les fichiers temporaires.'],
      ['Le suivi change de joueur lors d’un chevauchement', 'Arrêtez-vous à la dernière image fiable, choisissez **Refaire le suivi d’ici**, sélectionnez le bon joueur provisoire et continuez. **Annuler** conserve la fin d’origine.'],
      ['Le rapport d’intégrité signale un élément manquant', 'Restaurez-le depuis `.trash` si possible, ou retirez la référence cassée de la présentation. Annotate indique le chemin au lieu de réécrire votre travail sans le dire.'],
    ],
  },
  onThisPage: [
    ['videos', 'Tutoriels vidéo'],
    ['first-project', 'Premier projet'],
    ['capture', 'Capture'],
    ['clip-editor', 'Éditeur de clip'],
    ['tracking', 'Suivi'],
    ['pins', 'Repères'],
    ['homography', 'Dessin sur le terrain'],
    ['presentations', 'Présentations'],
    ['export-recovery', 'Export'],
    ['keyboard', 'Raccourcis'],
    ['glossary', 'Glossaire'],
  ],
};
